"""Initial migration

Revision ID: 72a137a8382c
Revises: 
Create Date: 2025-12-24 18:57:17.411159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = '72a137a8382c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_faculties_code', 'faculties', ['code'], unique=False)
    op.create_index(op.f('ix_faculties_code'), 'faculties', ['code'], unique=True)
    op.create_index(op.f('ix_faculties_name'), 'faculties', ['name'], unique=True)
    op.create_table('terms',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='check_term_date_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_terms_active', 'terms', ['is_active'], unique=False)
    op.create_index(op.f('ix_terms_is_active'), 'terms', ['is_active'], unique=False)
    op.create_table('departments',
    sa.Column('faculty_id', UUID(as_uuid=True), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'code', name='uq_department_faculty_code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_departments_faculty', 'departments', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_departments_faculty_id'), 'departments', ['faculty_id'], unique=False)
    op.create_table('time_slots',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('term_id', UUID(as_uuid=True), nullable=False),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', name='dayofweek'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'day_of_week', 'start_time', name='uq_time_slot')
    )
    op.create_index('idx_time_slots_term_day', 'time_slots', ['term_id', 'day_of_week'], unique=False)
    op.create_index(op.f('ix_time_slots_term_id'), 'time_slots', ['term_id'], unique=False)
    op.create_table('classrooms',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('classroom_type', sa.Enum('CLASSROOM', 'AMPHI', 'LAB', name='classroomtype'), nullable=False),
    sa.Column('department_id', UUID(as_uuid=True), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity BETWEEN 1 AND 300', name='check_capacity'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_classrooms_department', 'classrooms', ['department_id'], unique=False)
    op.create_index(op.f('ix_classrooms_is_active'), 'classrooms', ['is_active'], unique=False)
    op.create_table('courses',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department_id', UUID(as_uuid=True), nullable=True),
    sa.Column('term_id', UUID(as_uuid=True), nullable=False),
    sa.Column('class_level', sa.Enum('FIRST_YEAR', 'SECOND_YEAR', 'THIRD_YEAR', 'FOURTH_YEAR', name='courselevel'), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('course_type', sa.Enum('THEORY', 'LAB', 'PRACTICE', name='coursetype'), nullable=False),
    sa.Column('parent_course_id', UUID(as_uuid=True), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_retake_critical', sa.Boolean(), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weekly_hours IN (1,2,3,4,5,6,7,8,9)', name='check_weekly_hours'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'term_id', name='uq_course_code_term')
    )
    op.create_index('idx_courses_code', 'courses', ['code'], unique=False)
    op.create_index('idx_courses_term', 'courses', ['term_id'], unique=False)
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    op.create_index(op.f('ix_courses_term_id'), 'courses', ['term_id'], unique=False)
    op.create_table('instructors',
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Enum('PROF_DR', 'DOC_DR', 'DR_OGR_UYESI', 'OGR_GOR', 'ARS_GOR', name='instructortitle'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('home_department_id', UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['home_department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_instructors_email', 'instructors', ['email'], unique=False)
    op.create_index('idx_instructors_home_dept', 'instructors', ['home_department_id'], unique=False)
    op.create_index(op.f('ix_instructors_email'), 'instructors', ['email'], unique=True)
    op.create_index(op.f('ix_instructors_home_department_id'), 'instructors', ['home_department_id'], unique=False)
    op.create_index(op.f('ix_instructors_is_active'), 'instructors', ['is_active'], unique=False)
    op.create_table('program_classes',
    sa.Column('department_id', UUID(as_uuid=True), nullable=False),
    sa.Column('term_id', UUID(as_uuid=True), nullable=False),
    sa.Column('class_level', sa.Enum('FIRST', 'SECOND', 'THIRD', 'FOURTH', name='classlevel'), nullable=False),
    sa.Column('group_no', sa.Integer(), nullable=False),
    sa.Column('label', sa.Enum('FIRST_YEAR', 'SECOND_YEAR', 'THIRD_YEAR', 'FOURTH_YEAR', name='classlabel'), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'term_id', 'class_level', 'group_no', name='uq_program_class')
    )
    op.create_index(op.f('ix_program_classes_department_id'), 'program_classes', ['department_id'], unique=False)
    op.create_index(op.f('ix_program_classes_term_id'), 'program_classes', ['term_id'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DEAN', 'DEPARTMENT_REP', name='userrole'), nullable=False),
    sa.Column('department_id', UUID(as_uuid=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_department', 'users', ['department_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('course_offerings',
    sa.Column('course_id', UUID(as_uuid=True), nullable=False),
    sa.Column('instructor_id', UUID(as_uuid=True), nullable=False),
    sa.Column('classroom_id', UUID(as_uuid=True), nullable=False),
    sa.Column('term_id', UUID(as_uuid=True), nullable=False),
    sa.Column('group_no', sa.Integer(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('student_count BETWEEN 1 AND 300', name='check_student_count'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'term_id', 'group_no', name='uq_course_offering')
    )
    op.create_index('idx_course_offerings_composite', 'course_offerings', ['course_id', 'term_id', 'instructor_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_course_id'), 'course_offerings', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_instructor_id'), 'course_offerings', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_term_id'), 'course_offerings', ['term_id'], unique=False)
    op.create_table('instructor_availability',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('term_id', UUID(as_uuid=True), nullable=False),
    sa.Column('instructor_id', UUID(as_uuid=True), nullable=False),
    sa.Column('time_slot_id', UUID(as_uuid=True), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_by', UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term_id', 'instructor_id', 'time_slot_id', name='uq_instructor_availability')
    )
    op.create_index('idx_instructor_avail_composite', 'instructor_availability', ['term_id', 'instructor_id', 'time_slot_id'], unique=False)
    op.create_index(op.f('ix_instructor_availability_instructor_id'), 'instructor_availability', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_instructor_availability_term_id'), 'instructor_availability', ['term_id'], unique=False)
    op.create_index(op.f('ix_instructor_availability_time_slot_id'), 'instructor_availability', ['time_slot_id'], unique=False)
    op.create_table('schedules',
    sa.Column('term_id', UUID(as_uuid=True), nullable=False),
    sa.Column('department_id', UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='schedulestatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', UUID(as_uuid=True), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('evaluated_by', UUID(as_uuid=True), nullable=True),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedules_status', 'schedules', ['status'], unique=False)
    op.create_index('idx_schedules_term_dept', 'schedules', ['term_id', 'department_id'], unique=False)
    op.create_index(op.f('ix_schedules_department_id'), 'schedules', ['department_id'], unique=False)
    op.create_index(op.f('ix_schedules_status'), 'schedules', ['status'], unique=False)
    op.create_index(op.f('ix_schedules_term_id'), 'schedules', ['term_id'], unique=False)
    op.create_table('schedule_assignments',
    sa.Column('schedule_id', UUID(as_uuid=True), nullable=False),
    sa.Column('course_offering_id', UUID(as_uuid=True), nullable=False),
    sa.Column('time_slot_id', UUID(as_uuid=True), nullable=False),
    sa.Column('classroom_id', UUID(as_uuid=True), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'course_offering_id', 'time_slot_id', name='uq_schedule_assignment')
    )
    op.create_index('idx_schedule_assignments_composite', 'schedule_assignments', ['schedule_id', 'time_slot_id', 'classroom_id'], unique=False)
    op.create_index(op.f('ix_schedule_assignments_schedule_id'), 'schedule_assignments', ['schedule_id'], unique=False)
    op.create_table('schedule_review_notes',
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('schedule_id', UUID(as_uuid=True), nullable=False),
    sa.Column('note_type', sa.Enum('CONFLICT', 'SUGGESTION', 'APPROVAL', 'REJECTION', name='reviewnotetype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_by', UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_notes_schedule', 'schedule_review_notes', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_review_notes_schedule_id'), 'schedule_review_notes', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_review_notes_schedule_id'), table_name='schedule_review_notes')
    op.drop_index('idx_review_notes_schedule', table_name='schedule_review_notes')
    op.drop_table('schedule_review_notes')
    op.drop_index(op.f('ix_schedule_assignments_schedule_id'), table_name='schedule_assignments')
    op.drop_index('idx_schedule_assignments_composite', table_name='schedule_assignments')
    op.drop_table('schedule_assignments')
    op.drop_index(op.f('ix_schedules_term_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_status'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_department_id'), table_name='schedules')
    op.drop_index('idx_schedules_term_dept', table_name='schedules')
    op.drop_index('idx_schedules_status', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_instructor_availability_time_slot_id'), table_name='instructor_availability')
    op.drop_index(op.f('ix_instructor_availability_term_id'), table_name='instructor_availability')
    op.drop_index(op.f('ix_instructor_availability_instructor_id'), table_name='instructor_availability')
    op.drop_index('idx_instructor_avail_composite', table_name='instructor_availability')
    op.drop_table('instructor_availability')
    op.drop_index(op.f('ix_course_offerings_term_id'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_instructor_id'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_course_id'), table_name='course_offerings')
    op.drop_index('idx_course_offerings_composite', table_name='course_offerings')
    op.drop_table('course_offerings')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_department', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_program_classes_term_id'), table_name='program_classes')
    op.drop_index(op.f('ix_program_classes_department_id'), table_name='program_classes')
    op.drop_table('program_classes')
    op.drop_index(op.f('ix_instructors_is_active'), table_name='instructors')
    op.drop_index(op.f('ix_instructors_home_department_id'), table_name='instructors')
    op.drop_index(op.f('ix_instructors_email'), table_name='instructors')
    op.drop_index('idx_instructors_home_dept', table_name='instructors')
    op.drop_index('idx_instructors_email', table_name='instructors')
    op.drop_table('instructors')
    op.drop_index(op.f('ix_courses_term_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_index('idx_courses_term', table_name='courses')
    op.drop_index('idx_courses_code', table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_classrooms_is_active'), table_name='classrooms')
    op.drop_index('idx_classrooms_department', table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_time_slots_term_id'), table_name='time_slots')
    op.drop_index('idx_time_slots_term_day', table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_index(op.f('ix_departments_faculty_id'), table_name='departments')
    op.drop_index('idx_departments_faculty', table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_terms_is_active'), table_name='terms')
    op.drop_index('idx_terms_active', table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_faculties_name'), table_name='faculties')
    op.drop_index(op.f('ix_faculties_code'), table_name='faculties')
    op.drop_index('idx_faculties_code', table_name='faculties')
    op.drop_table('faculties')
    # ### end Alembic commands ###

